name: 'Publish Policy'
description: 'Publish a single policy version to S3 and Policy Hub'

inputs:
  policy:
    description: 'Policy name'
    required: true
  version:
    description: 'Policy version'
    required: true
  s3-bucket:
    description: 'S3 bucket name'
    required: true
  policy-hub-url:
    description: 'Policy Hub API URL'
    required: true
  repo-url:
    description: 'GitHub repository URL'
    required: true
  policy-hub-api-key:
    description: 'Policy Hub API key'
    required: true
  source-type:
    description: 'Source type: github or s3'
    required: false
    default: 'github'

outputs:
  success:
    description: 'Whether the policy was successfully published'
    value: ${{ steps.result.outputs.success }}

runs:
  using: 'composite'
  steps:
    - name: Prepare ZIP
      id: prepare
      run: |
        if ./scripts/prepare-zip.sh "${{ inputs.policy }}" "${{ inputs.version }}"; then
          echo "✅ ZIP prepared successfully"
          echo "success=true" >> $GITHUB_OUTPUT
        else
          echo "❌ ZIP preparation failed"
          echo "success=false" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Upload to S3 or GitHub Release
      id: upload
      if: steps.prepare.outputs.success == 'true'
      run: |
        zip_file="${{ inputs.policy }}-${{ inputs.version }}.zip"
        
        # Read source type from config or use input
        config_file="config/policy-hub-config.json"
        if [ -f "$config_file" ]; then
          config_source_type=$(jq -r '.policyHub.sourceType // "github"' "$config_file")
        else
          config_source_type="github"
        fi
        
        # Use input source-type if provided, otherwise use config
        source_type="${{ inputs.source-type }}"
        if [[ -z "$source_type" || "$source_type" == "github" ]]; then
          source_type="$config_source_type"
        fi
        
        if [[ "$source_type" == "s3" ]]; then
          # Upload to S3
          s3_path="s3://${{ inputs.s3-bucket }}/policies/$zip_file"
          if aws s3 cp "$zip_file" "$s3_path" --no-progress; then
            echo "✅ Uploaded to $s3_path"
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "❌ S3 upload failed"
            echo "success=false" >> $GITHUB_OUTPUT
          fi
        else
          # Upload to GitHub Release
          if gh release upload "${{ inputs.version }}" "$zip_file" --clobber; then
            echo "✅ Uploaded to GitHub release ${{ inputs.version }}"
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "❌ GitHub release upload failed"
            echo "success=false" >> $GITHUB_OUTPUT
          fi
        fi
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Sync with Policy Hub
      id: sync
      if: steps.upload.outputs.success == 'true'
      run: |
        policy_dir="policies/${{ inputs.policy }}/${{ inputs.version }}"

        # Read metadata
        if [ -f "$policy_dir/metadata.json" ]; then
          display_name=$(jq -r '.displayName // "Unknown"' "$policy_dir/metadata.json")
          provider=$(jq -r '.provider // "Unknown"' "$policy_dir/metadata.json")
          description=$(jq -r '.description // ""' "$policy_dir/metadata.json")
          categories=$(jq -r '.categories // [] | map("\"" + . + "\"") | join(",")' "$policy_dir/metadata.json")
          tags=$(jq -r '.tags // [] | map("\"" + . + "\"") | join(",")' "$policy_dir/metadata.json")
          supported_platforms=$(jq -r '.supportedPlatforms // [] | map("\"" + . + "\"") | join(",")' "$policy_dir/metadata.json")
          logo_url=$(jq -r '.logoUrl // ""' "$policy_dir/metadata.json")
          banner_url=$(jq -r '.bannerUrl // ""' "$policy_dir/metadata.json")
          
          # Convert GitHub URLs to raw if needed
          if [[ "$logo_url" =~ ^https://github\.com/ ]]; then
            logo_url=$(echo "$logo_url" | sed 's|https://github.com/|https://raw.githubusercontent.com/|' | sed 's|/blob/|/|')
          fi
          if [[ "$banner_url" =~ ^https://github\.com/ ]]; then
            banner_url=$(echo "$banner_url" | sed 's|https://github.com/|https://raw.githubusercontent.com/|' | sed 's|/blob/|/|')
          fi
        else
          echo "⚠️  metadata.json not found, using defaults"
          display_name="Unknown"
          provider="Unknown"
          description=""
          categories=""
          tags=""
          supported_platforms=""
          logo_url=""
          banner_url=""
        fi

        # Read source type from config or use input
        config_file="config/policy-hub-config.json"
        if [ -f "$config_file" ]; then
          config_source_type=$(jq -r '.policyHub.sourceType // "github"' "$config_file")
        else
          config_source_type="github"
        fi
        
        # Use input source-type if provided, otherwise use config
        source_type="${{ inputs.source-type }}"
        if [[ -z "$source_type" || "$source_type" == "github" ]]; then
          source_type="$config_source_type"
        fi
        
        # Extract repo details for raw.githubusercontent.com URLs
        repo_path=$(echo "${{ inputs.repo-url }}" | sed 's|https://github.com/||')
        
        # Determine source URL based on source type
        if [[ "$source_type" == "s3" ]]; then
          source_url="https://${{ inputs.s3-bucket }}.s3.${{ env.AWS_REGION || 'us-east-1' }}.amazonaws.com/policies/${{ inputs.policy }}-${{ inputs.version }}.zip"
        else
          # GitHub raw URL for the policy directory
          source_url="https://raw.githubusercontent.com/$repo_path/main/policies/${{ inputs.policy }}/${{ inputs.version }}"
        fi

        # Always use GitHub raw URLs for policy resources (definition, docs, assets)
        base_url="https://raw.githubusercontent.com/$repo_path/main/$policy_dir"
        definition_url="$base_url/policy-definition.yaml"
        docs_base_url="$base_url/docs/"
        assets_base_url="$base_url/assets/"

        # Construct API payload matching the expected structure
        payload=$(cat <<EOF
        {
          "policyName": "${{ inputs.policy }}",
          "version": "${{ inputs.version }}",
          "sourceType": "$source_type",
          "sourceUrl": "$source_url",
          "definitionUrl": "$definition_url",
          "metadata": {
            "displayName": "$display_name",
            "provider": "$provider",
            "description": "$description",
            "categories": [$categories],
            "tags": [$tags],
            "supportedPlatforms": [$supported_platforms],
            "logoUrl": "$logo_url",
            "bannerUrl": "$banner_url"
          },
          "documentation": {
            "configuration": "$docs_base_url/configuration.md",
            "examples": "$docs_base_url/examples.md",
            "overview": "$docs_base_url/overview.md"
          },
          "assetsBaseUrl": "$assets_base_url"
        }
        EOF
        )

        sync_url="${{ inputs.policy-hub-url }}/sync"
        echo "🔗 Syncing with Policy Hub: $sync_url"
        echo "📝 Payload: $payload"
        
        # Make API call with retry logic
        max_retries=3
        retry_count=0
        success=false
        
        while [ $retry_count -lt $max_retries ] && [ "$success" = false ]; do
          echo "Attempting sync (attempt $((retry_count + 1))/$max_retries)..."
          
          response=$(curl -X POST "$sync_url" \
            -H "Authorization: Bearer $POLICY_HUB_API_KEY" \
            -H "Content-Type: application/json" \
            -H "User-Agent: GitHub-Actions-Policy-Publish" \
            -H "ngrok-skip-browser-warning: true" \
            -d "$payload" \
            --max-time 30 \
            --connect-timeout 10 \
            --retry 0 \
            -w "HTTP_CODE:%{http_code}" \
            -s)
          
          http_code=$(echo "$response" | grep -o "HTTP_CODE:[0-9]*" | cut -d: -f2)
          response_body=$(echo "$response" | sed 's/HTTP_CODE:[0-9]*$//')
          
          if [[ "$http_code" -ge 200 && "$http_code" -lt 300 ]]; then
            api_success=$(echo "$response_body" | jq -r '.success // false' 2>/dev/null || echo "false")
            if [[ "$api_success" == "true" ]]; then
              success=true
              echo "✅ Synced successfully on attempt $((retry_count + 1))"
            else
              echo "❌ API returned success=false on attempt $((retry_count + 1))"
            fi
          else
            echo "❌ HTTP $http_code on attempt $((retry_count + 1))"
          fi
          
          if [ "$success" = false ]; then
            retry_count=$((retry_count + 1))
            if [ $retry_count -lt $max_retries ]; then
              echo "Retrying in 5 seconds..."
              sleep 5
            fi
          fi
        done
        
        if [ "$success" = true ]; then
          policy_name=$(echo "$response_body" | jq -r '.data.policyName // "unknown"' 2>/dev/null)
          version=$(echo "$response_body" | jq -r '.data.version // "unknown"' 2>/dev/null)
          status=$(echo "$response_body" | jq -r '.data.status // "unknown"' 2>/dev/null)
          trace_id=$(echo "$response_body" | jq -r '.meta.trace_id // "none"' 2>/dev/null)
          
          echo "📊 Policy: $policy_name $version, Status: $status, Trace: $trace_id"
          echo "success=true" >> $GITHUB_OUTPUT
        else
          error_msg=$(echo "$response_body" | jq -r '.error // "Unknown error"' 2>/dev/null)
          echo "❌ Sync failed after $max_retries attempts"
          echo "Final error: $error_msg"
          echo "Final response: $response_body"
          echo "success=false" >> $GITHUB_OUTPUT
        fi
      shell: bash
      env:
        POLICY_HUB_API_KEY: ${{ inputs.policy-hub-api-key }}

    - name: Cleanup
      if: always()
      run: rm -f "${{ inputs.policy }}-${{ inputs.version }}.zip"
      shell: bash

    - name: Set final result
      id: result
      run: |
        prepare_success="${{ steps.prepare.outputs.success }}"
        upload_success="${{ steps.upload.outputs.success }}"
        sync_success="${{ steps.sync.outputs.success }}"
        
        echo "Debug - prepare: $prepare_success, upload: $upload_success, sync: $sync_success"
        
        if [[ "$prepare_success" == "true" && \
              "$upload_success" == "true" && \
              "$sync_success" == "true" ]]; then
          echo "success=true" >> $GITHUB_OUTPUT
          echo "✅ All steps completed successfully"
        else
          echo "success=false" >> $GITHUB_OUTPUT
          echo "❌ One or more steps failed"
        fi
      shell: bash