name: 'Publish Policy'
description: 'Publish a single policy version to S3 and Policy Hub'

inputs:
  policy:
    description: 'Policy name'
    required: true
  version:
    description: 'Policy version'
    required: true
  s3-bucket:
    description: 'S3 bucket name'
    required: true
  policy-hub-url:
    description: 'Policy Hub API URL'
    required: true
  repo-url:
    description: 'GitHub repository URL'
    required: true
  policy-hub-api-key:
    description: 'Policy Hub API key'
    required: true
  source-type:
    description: 'Source type: github or s3'
    required: false
    default: 'github'

runs:
  using: 'composite'
  steps:
    - name: Prepare ZIP
      id: prepare
      run: |
        if ./scripts/prepare-zip.sh "${{ inputs.policy }}" "${{ inputs.version }}"; then
          echo "✅ ZIP prepared successfully"
          echo "success=true" >> $GITHUB_OUTPUT
        else
          echo "❌ ZIP preparation failed"
          echo "success=false" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Upload to S3 or GitHub Release
      id: upload
      if: steps.prepare.outputs.success == 'true'
      run: |
        zip_file="${{ inputs.policy }}-${{ inputs.version }}.zip"
        
        # Read source type from config or use input
        config_file="config/policy-hub-config.json"
        if [ -f "$config_file" ]; then
          config_source_type=$(jq -r '.policyHub.sourceType // "github"' "$config_file")
        else
          config_source_type="github"
        fi
        
        # Use input source-type if provided, otherwise use config
        source_type="${{ inputs.source-type }}"
        if [[ -z "$source_type" || "$source_type" == "github" ]]; then
          source_type="$config_source_type"
        fi
        
        if [[ "$source_type" == "s3" ]]; then
          # Upload to S3
          s3_path="s3://${{ inputs.s3-bucket }}/policies/$zip_file"
          if aws s3 cp "$zip_file" "$s3_path" --no-progress; then
            echo "✅ Uploaded to $s3_path"
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "❌ S3 upload failed"
            echo "success=false" >> $GITHUB_OUTPUT
          fi
        else
          # Upload to GitHub Release
          if gh release upload "${{ inputs.version }}" "$zip_file" --clobber; then
            echo "✅ Uploaded to GitHub release ${{ inputs.version }}"
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "❌ GitHub release upload failed"
            echo "success=false" >> $GITHUB_OUTPUT
          fi
        fi
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Sync with Policy Hub
      id: sync
      if: steps.upload.outputs.success == 'true'
      run: |
        policy_dir="policies/${{ inputs.policy }}/${{ inputs.version }}"

        # Read metadata
        if [ -f "$policy_dir/metadata.json" ]; then
          metadata=$(cat "$policy_dir/metadata.json")
        else
          echo "⚠️  metadata.json not found, using empty object"
          metadata="{}"
        fi

        # Read source type from config or use input
        config_file="config/policy-hub-config.json"
        if [ -f "$config_file" ]; then
          config_source_type=$(jq -r '.policyHub.sourceType // "github"' "$config_file")
        else
          config_source_type="github"
        fi
        
        # Use input source-type if provided, otherwise use config
        source_type="${{ inputs.source-type }}"
        if [[ -z "$source_type" || "$source_type" == "github" ]]; then
          source_type="$config_source_type"
        fi
        
        # Determine source URL based on source type
        if [[ "$source_type" == "s3" ]]; then
          source_url="https://${{ inputs.s3-bucket }}.s3.${{ env.AWS_REGION || 'us-east-1' }}.amazonaws.com/policies/${{ inputs.policy }}-${{ inputs.version }}.zip"
        else
          # GitHub raw repository URL for direct file access
          source_url="${{ inputs.repo-url }}/raw/main/policies/${{ inputs.policy }}/${{ inputs.version }}"
          source_type="github"
        fi

        # Always use GitHub raw URLs for policy resources (definition, docs, assets)
        base_url="${{ inputs.repo-url }}/raw/main/$policy_dir"
        definition_url="$base_url/policy-definition.yaml"
        docs_base_url="$base_url/docs/"
        assets_base_url="$base_url/assets/"

        # Construct API payload
        payload=$(cat <<EOF
        {
          "policyName": "${{ inputs.policy }}",
          "version": "${{ inputs.version }}",
          "sourceType": "$source_type",
          "sourceUrl": "$source_url",
          "definitionUrl": "$definition_url",
          "metadata": $metadata,
          "docsBaseUrl": "$docs_base_url",
          "assetsBaseUrl": "$assets_base_url"
        }
        EOF
        )

        sync_url="${{ inputs.policy-hub-url }}/sync"
        echo "🔗 Syncing with Policy Hub: $sync_url"
        echo "📝 Payload: $payload"
        
        response=$(curl -X POST "$sync_url" \
          -H "Authorization: Bearer $POLICY_HUB_API_KEY" \
          -H "Content-Type: application/json" \
          -H "ngrok-skip-browser-warning: true" \
          -d "$payload" \
          --max-time 30 \
          -w "HTTP_CODE:%{http_code}" \
          -s)
        
        http_code=$(echo "$response" | grep -o "HTTP_CODE:[0-9]*" | cut -d: -f2)
        response_body=$(echo "$response" | sed 's/HTTP_CODE:[0-9]*$//')
        
        if [[ "$http_code" -ge 200 && "$http_code" -lt 300 ]]; then
          echo "✅ Synced with Policy Hub (HTTP $http_code)"
          echo "success=true" >> $GITHUB_OUTPUT
        else
          echo "❌ Policy Hub sync failed (HTTP $http_code)"
          echo "Response: $response_body"
          echo "success=false" >> $GITHUB_OUTPUT
        fi
      shell: bash
      env:
        POLICY_HUB_API_KEY: ${{ inputs.policy-hub-api-key }}

    - name: Cleanup
      if: always()
      run: rm -f "${{ inputs.policy }}-${{ inputs.version }}.zip"
      shell: bash

    - name: Set final result
      id: result
      run: |
        if [[ "${{ steps.prepare.outputs.success }}" == "true" && \
              "${{ steps.upload.outputs.success }}" == "true" && \
              "${{ steps.sync.outputs.success }}" == "true" ]]; then
          echo "success=true" >> $GITHUB_OUTPUT
        else
          echo "success=false" >> $GITHUB_OUTPUT
        fi
      shell: bash