name: 'Policy Operations'
description: 'Combined action for policy validation, status check, and publishing'
inputs:
  operation:
    description: 'Operation to perform: detect, validate, check-status, check-api-existence, publish, update-state'
    required: true
  policy-path:
    description: 'Policy folder path'
    required: false
  policy-name:
    description: 'Policy name'
    required: false
  policy-version:
    description: 'Policy version'
    required: false
  policy-sha:
    description: 'Policy SHA'
    required: false
  baseline-sha:
    description: 'Baseline SHA for detection'
    required: false
  api-url:
    description: 'Policy Hub API URL'
    required: false
  api-key:
    description: 'API key'
    required: false
  release-tag:
    description: 'Release tag'
    required: false
  config-file:
    description: 'Config file path'
    required: false
    default: 'config/policy-hub-config.json'
  state-file:
    description: 'State file path'
    required: false
    default: '.state/delivered.json'
  workspace:
    description: 'Workspace path'
    required: true
    default: '.'
outputs:
  # Detection outputs
  changed-policies:
    description: 'Changed policies (JSON)'
  changed-policies-matrix:
    description: 'Matrix format'
  policy-count:
    description: 'Policy count'
  # Validation outputs
  valid:
    description: 'Is valid'
  validation-errors:
    description: 'Validation errors'
  validation-warnings:
    description: 'Validation warnings'
  # Status check outputs
  should-deliver:
    description: 'Should deliver'
  delivery-reason:
    description: 'Delivery reason'
  last-delivered-sha:
    description: 'Last delivered SHA'
  # API existence check outputs
  api-available:
    description: 'Is API available'
  policy-exists-in-api:
    description: 'Policy exists in API'
  should-skip:
    description: 'Should skip processing'
  check-result:
    description: 'Check result: exists-in-api, not-in-api, api-unavailable, check-failed'
  # Publishing outputs
  published:
    description: 'Published successfully'
  api-response:
    description: 'API response'
  policy-url:
    description: 'Policy URL'
  # State update outputs
  state-updated:
    description: 'State updated'
  previous-sha:
    description: 'Previous SHA'
runs:
  using: 'node20'
  main: 'index.js'