name: 'Detect New Policy Versions'
description: 'Detect new policy versions from git changes'

inputs:
  base-sha:
    description: 'Base SHA for comparison'
    required: true
  head-sha:
    description: 'Head SHA for comparison'
    required: true

outputs:
  new-versions:
    description: 'Space-separated list of new policy versions (policy/version format)'
    value: ${{ steps.detect.outputs.new_versions }}

runs:
  using: 'composite'
  steps:
    - name: Detect new versions
      id: detect
      run: |
        set -euo pipefail
        
        base_sha="${{ inputs.base-sha }}"
        head_sha="${{ inputs.head-sha }}"
        
        echo "🔍 Detecting new policy versions..."
        echo "Base SHA: $base_sha"
        echo "Head SHA: $head_sha"

        # Validate input SHAs
        if [[ -z "$base_sha" || -z "$head_sha" ]]; then
          echo "❌ Error: Both base-sha and head-sha are required"
          exit 1
        fi

        # Check if base-sha is valid
        if ! git rev-parse --verify "$base_sha" >/dev/null 2>&1; then
          echo "⚠️  Base SHA $base_sha not found. Skipping diff."
          echo "new_versions=" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Check if head-sha is valid
        if ! git rev-parse --verify "$head_sha" >/dev/null 2>&1; then
          echo "⚠️  Head SHA $head_sha not found. Skipping diff."
          echo "new_versions=" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Get added files in policies/ directory
        raw_diff=$(git diff --name-only --diff-filter=A "$base_sha" "$head_sha" 2>/dev/null || echo "")
        
        if [[ -z "$raw_diff" ]]; then
          echo "ℹ️  No new files detected between commits"
          echo "new_versions=" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        added_files=$(echo "$raw_diff" | grep '^policies/' | sort | uniq || echo "")
        
        if [[ -z "$added_files" ]]; then
          echo "ℹ️  No new policy files detected"
          echo "new_versions=" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        echo "📁 Found $(echo "$added_files" | wc -l) new file(s) in policies/"

        # Extract unique policy/version pairs
        declare -A seen_versions
        new_versions=""
        
        while IFS= read -r file; do
          if [[ $file =~ ^policies/([a-zA-Z0-9_-]+)/([v0-9.]+)/ ]]; then
            policy="${BASH_REMATCH[1]}"
            version="${BASH_REMATCH[2]}"
            version_path="${policy}/${version}"
            
            # Use associative array for deduplication
            if [[ -z "${seen_versions[$version_path]:-}" ]]; then
              seen_versions[$version_path]=1
              new_versions="$new_versions $version_path"
            fi
          fi
        done <<< "$added_files"

        # Sort and clean up
        new_versions=$(echo $new_versions | tr ' ' '\n' | sort | uniq | tr '\n' ' ' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
        echo "new_versions=$new_versions" >> $GITHUB_OUTPUT

        if [ -n "$new_versions" ]; then
          version_count=$(echo "$new_versions" | wc -w)
          echo "📦 Detected $version_count new policy version(s):"
          echo "$new_versions" | tr ' ' '\n' | sed 's/^/  - /'
        else
          echo "ℹ️  No new policy versions detected"
        fi
      shell: bash