name: 'Detect New Policy Versions'
description: 'Detect new policy versions from git changes'

inputs:
  base-sha:
    description: 'Base SHA for comparison'
    required: true
  head-sha:
    description: 'Head SHA for comparison'
    required: true

outputs:
  new-versions:
    description: 'Space-separated list of new policy versions (policy/version format)'
    value: ${{ steps.detect.outputs.new_versions }}

runs:
  using: 'composite'
  steps:
    - name: Verify Policy Hub API URL
      run: |
        echo "🔗 Verifying Policy Hub API URL: $POLICY_HUB_API_URL"
        if curl --max-time 10 -H "ngrok-skip-browser-warning: true" "$POLICY_HUB_API_URL/health" >/dev/null 2>&1; then
          echo "✅ Policy Hub API URL is reachable."
        else
          echo "❌ Policy Hub API URL is not reachable or returned an error."
          exit 1
        fi
      shell: bash
    - name: Detect new versions
      id: detect
      run: |
        echo "🔍 Detecting new policy versions..."
        echo "Base SHA: ${{ inputs.base-sha }}"
        echo "Head SHA: ${{ inputs.head-sha }}"

        # Check if base-sha is valid
        if ! git rev-parse --verify "${{ inputs.base-sha }}" >/dev/null 2>&1; then
          echo "Base SHA ${{ inputs.base-sha }} not found. Skipping diff."
          echo "new_versions=" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Check if head-sha is valid
        if ! git rev-parse --verify "${{ inputs.head-sha }}" >/dev/null 2>&1; then
          echo "Head SHA ${{ inputs.head-sha }} not found. Skipping diff."
          echo "new_versions=" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Get added files in policies/
        raw_diff=$(git diff --name-only --diff-filter=A "${{ inputs.base-sha }}" "${{ inputs.head-sha }}" 2>/dev/null || echo "")
        echo "Debug: Raw git diff output: $raw_diff"
        added_files=$(echo "$raw_diff" | grep '^policies/' | sort | uniq || echo "")
        echo "Debug: Added files in policies/: $added_files"

        new_versions=""
        for file in $added_files; do
          if [[ $file =~ ^policies/([^/]+)/([^/]+)/ ]]; then
            version_path="${BASH_REMATCH[1]}/${BASH_REMATCH[2]}"
            if [[ ! " $new_versions " =~ " $version_path " ]]; then
              new_versions="$new_versions $version_path"
            fi
          fi
        done

        new_versions=$(echo $new_versions | tr ' ' '\n' | sort | uniq | tr '\n' ' ' | sed 's/[[:space:]]*$//')
        echo "new_versions=$new_versions" >> $GITHUB_OUTPUT

        if [ -n "$new_versions" ]; then
          echo "📦 New versions detected:"
          echo "$new_versions" | tr ' ' '\n' | sed 's/^/- /'
        else
          echo "ℹ️  No new policy versions detected"
        fi
      shell: bash